import { MigrateUpArgs, MigrateDownArgs, sql } from '@payloadcms/db-postgres'

export async function up({ db, payload, req }: MigrateUpArgs): Promise<void> {
  await db.execute(sql`
   CREATE TYPE "public"."enum_pages_page_template" AS ENUM('default', 'template-a', 'template-b', 'template-c', 'template-d');
  CREATE TYPE "public"."enum__pages_v_version_page_template" AS ENUM('default', 'template-a', 'template-b', 'template-c', 'template-d');
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_hero" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_stats" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_services" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_featured_products" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_about" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_rich_text" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_gallery" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_gallery_full" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_testimonials" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_cta" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_faq" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_pricing" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_steps" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_contact_form" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_legal_text" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_partners" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_team" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_map_area" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "animation" varchar;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "pages_blocks_offer_cards" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "pages" ADD COLUMN "page_template" "enum_pages_page_template" DEFAULT 'default';
  ALTER TABLE "pages" ADD COLUMN "global_css_overlay" varchar;
  ALTER TABLE "pages" ADD COLUMN "layout_css_overlay" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_hero" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_stats" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_services" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_featured_products" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_about" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_rich_text" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_gallery" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_gallery_full" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_testimonials" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_cta" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_faq" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_pricing" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_steps" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_contact_form" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_legal_text" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_partners" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_team" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_map_area" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "animation" varchar;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "animation_duration" numeric;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "animation_delay" numeric;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "animation_easing" varchar;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "animation_iterations" varchar;
  ALTER TABLE "_pages_v_blocks_offer_cards" ADD COLUMN "style_overrides" jsonb;
  ALTER TABLE "_pages_v" ADD COLUMN "version_page_template" "enum__pages_v_version_page_template" DEFAULT 'default';
  ALTER TABLE "_pages_v" ADD COLUMN "version_global_css_overlay" varchar;
  ALTER TABLE "_pages_v" ADD COLUMN "version_layout_css_overlay" varchar;`)
}

export async function down({ db, payload, req }: MigrateDownArgs): Promise<void> {
  await db.execute(sql`
   ALTER TABLE "pages_blocks_hero" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_hero" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_stats" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_services" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_featured_products" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_about" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_rich_text" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_gallery" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_gallery_full" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_testimonials" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_cta" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_faq" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_pricing" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_steps" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_contact_form" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_legal_text" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_partners" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_team" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_map_area" DROP COLUMN "style_overrides";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "animation";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "animation_duration";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "animation_delay";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "animation_easing";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "animation_iterations";
  ALTER TABLE "pages_blocks_offer_cards" DROP COLUMN "style_overrides";
  ALTER TABLE "pages" DROP COLUMN "page_template";
  ALTER TABLE "pages" DROP COLUMN "global_css_overlay";
  ALTER TABLE "pages" DROP COLUMN "layout_css_overlay";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_hero" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_stats" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_services" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_featured_products" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_about" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_rich_text" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_gallery" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_gallery_full" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_testimonials" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_cta" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_faq" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_pricing" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_steps" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_contact_form" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_legal_text" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_partners" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_team" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_map_area" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "animation";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "animation_duration";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "animation_delay";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "animation_easing";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "animation_iterations";
  ALTER TABLE "_pages_v_blocks_offer_cards" DROP COLUMN "style_overrides";
  ALTER TABLE "_pages_v" DROP COLUMN "version_page_template";
  ALTER TABLE "_pages_v" DROP COLUMN "version_global_css_overlay";
  ALTER TABLE "_pages_v" DROP COLUMN "version_layout_css_overlay";
  DROP TYPE "public"."enum_pages_page_template";
  DROP TYPE "public"."enum__pages_v_version_page_template";`)
}
