#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────
# gen-secrets.sh — Generate a complete .env file
# ──────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ROOT_DIR="$(cd "$SCRIPT_DIR/../.." && pwd)"
ENV_FILE="$ROOT_DIR/apps/web/.env"
EXAMPLE_FILE="$ROOT_DIR/ops/.env.example"

# ── Colours ──────────────────────────────────
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

info()  { echo -e "${CYAN}ℹ ${NC}$*"; }
ok()    { echo -e "${GREEN}✅ ${NC}$*"; }
warn()  { echo -e "${YELLOW}⚠️  ${NC}$*"; }
err()   { echo -e "${RED}❌ ${NC}$*" >&2; }

# ── Pre-flight checks ───────────────────────
if ! command -v openssl &>/dev/null; then
  err "openssl is required but not installed."
  exit 1
fi

if [[ ! -f "$EXAMPLE_FILE" ]]; then
  err "Template not found: $EXAMPLE_FILE"
  exit 1
fi

# ── Handle existing .env ─────────────────────
FORCE=false
for arg in "$@"; do
  case "$arg" in
    --force|-f) FORCE=true ;;
    --help|-h)
      echo "Usage: $(basename "$0") [--force]"
      echo ""
      echo "Generates a complete .env file at apps/web/.env"
      echo "with auto-generated secrets and sensible defaults."
      echo ""
      echo "Options:"
      echo "  --force, -f   Overwrite existing .env file"
      echo "  --help,  -h   Show this help message"
      exit 0
      ;;
  esac
done

if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != true ]]; then
  warn ".env already exists at: $ENV_FILE"
  warn "Use --force to overwrite."
  exit 1
fi

# ── Generate secrets ─────────────────────────
PAYLOAD_SECRET="$(openssl rand -hex 32)"

info "Generating .env file..."

# ── Write .env ───────────────────────────────
mkdir -p "$(dirname "$ENV_FILE")"

cat > "$ENV_FILE" <<EOF
# ─────────────────────────────────────────────
# Forest Hub — Environment Configuration
# Generated by ops/scripts/gen-secrets.sh
# ─────────────────────────────────────────────

# Database
DATABASE_URI=postgresql://user:pass@localhost:5432/foresthub

# Payload CMS
PAYLOAD_SECRET=${PAYLOAD_SECRET}

# Builder.io
NEXT_PUBLIC_BUILDER_API_KEY=

# Site
NEXT_PUBLIC_SITE_URL=https://forestbar.pl
NO_INDEX=true

# SMTP (optional)
SMTP_HOST=
SMTP_PORT=587
SMTP_USER=
SMTP_PASS=
SMTP_FROM=kontakt@forestbar.pl

# Feature flags
NEXT_PUBLIC_ENABLE_3D=true
NEXT_PUBLIC_ENABLE_CUSTOM_CURSOR=true
EOF

ok ".env generated at: $ENV_FILE"
echo ""
info "Auto-generated secrets:"
echo "  PAYLOAD_SECRET ✔ (64-char hex)"
echo ""
warn "Remember to update DATABASE_URI, SMTP_*, and API keys before deploying."
